name: Build and Deploy APK

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    name: Build Debug APK and Push to output branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon
    - name: Upload Debug APK  
      uses: actions/upload-artifact@v4  
      with:  
        name: debug-apk-${{ github.run_number }}  
        path: app/build/outputs/apk/debug/app-debug.apk  
        retention-days: 30